name: Admin BDD Test 

on:
  push:
    branches:
      - main
    paths:
      - models/admin.js
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        
      - name:  Install Jsdom
        run: npm install jsdom
        
      - name: Run tests
        run: npm test
